//! Canonical social state: users, presence, relationships, guilds, channels,
//! conversations, messages, lobbies and voice.
//!
//! These are Litecord's *own* representations. Adapters convert SDK objects
//! into them; nothing here mirrors an SDK layout.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use crate::ids::*;
use crate::Timestamp;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct User {
    pub id: UserId,
    pub username: Arc<str>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub global_name: Option<Arc<str>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<Arc<str>>,
    #[serde(default)]
    pub is_bot: bool,
    /// Provisional (game-only) accounts created through the Social SDK.
    #[serde(default)]
    pub is_provisional: bool,
}

impl User {
    /// The name a UI should show by default.
    pub fn display_name(&self) -> &str {
        self.global_name.as_deref().unwrap_or(&self.username)
    }
}

str_enum! {
    pub enum PresenceStatus {
        Online => "online",
        Idle => "idle",
        DoNotDisturb => "dnd",
        Invisible => "invisible",
        Offline => "offline",
        Unknown => "unknown",
    }
}

#[allow(clippy::derivable_impls)] // the enum is generated by `str_enum!`
impl Default for PresenceStatus {
    fn default() -> Self {
        PresenceStatus::Unknown
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct Activity {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct Presence {
    pub status: PresenceStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub activity: Option<Activity>,
}

str_enum! {
    pub enum RelationshipKind {
        None => "none",
        Friend => "friend",
        Blocked => "blocked",
        PendingIncoming => "pending_incoming",
        PendingOutgoing => "pending_outgoing",
        Implicit => "implicit",
    }
}

/// A relationship between the current user and another user. The Social SDK
/// distinguishes Discord-wide and game-scoped relationships; both are kept.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Relationship {
    pub user_id: UserId,
    pub discord: RelationshipKind,
    pub game: RelationshipKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub since: Option<Timestamp>,
}

impl Relationship {
    pub fn is_friend(&self) -> bool {
        self.discord == RelationshipKind::Friend || self.game == RelationshipKind::Friend
    }
    pub fn is_blocked(&self) -> bool {
        self.discord == RelationshipKind::Blocked || self.game == RelationshipKind::Blocked
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Guild {
    pub id: GuildId,
    pub name: Arc<str>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<Arc<str>>,
}

str_enum! {
    pub enum ChannelKind {
        Text => "text",
        Voice => "voice",
        Category => "category",
        Announcement => "announcement",
        Forum => "forum",
        Thread => "thread",
        Stage => "stage",
        Other => "other",
    }
}

str_enum! {
    /// How a guild channel can be accessed from Litecord (V1 §13).
    pub enum ChannelAccess {
        Native => "native",
        Linked => "linked",
        DiscordOnly => "discord_only",
    }
}

/// Bit set of what can be done with a channel. Hand-rolled to avoid a
/// dependency for six flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ChannelCapabilities(pub u32);

impl ChannelCapabilities {
    pub const DISCOVERABLE: Self = Self(1 << 0);
    pub const READABLE: Self = Self(1 << 1);
    pub const WRITABLE: Self = Self(1 << 2);
    pub const LINKABLE: Self = Self(1 << 3);
    pub const VOICE: Self = Self(1 << 4);
    pub const OPEN_EXTERNAL: Self = Self(1 << 5);

    pub const fn empty() -> Self {
        Self(0)
    }
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }
}

impl std::ops::BitOr for ChannelCapabilities {
    type Output = Self;
    fn bitor(self, rhs: Self) -> Self {
        self.union(rhs)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Channel {
    pub id: ChannelId,
    pub guild_id: GuildId,
    pub name: Arc<str>,
    pub kind: ChannelKind,
    #[serde(default)]
    pub position: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<ChannelId>,
    pub access: ChannelAccess,
    pub capabilities: ChannelCapabilities,
}

str_enum! {
    pub enum ConversationKind {
        DirectMessage => "dm",
        GroupDm => "group_dm",
        Lobby => "lobby",
        GuildChannel => "guild_channel",
    }
}

/// A place where messages live. `id` is the Discord channel id.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Conversation {
    pub id: ConversationId,
    pub kind: ConversationKind,
    /// For DMs: the other participant.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipient_id: Option<UserId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<GuildId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lobby_id: Option<LobbyId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<Arc<str>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_message_id: Option<MessageId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_activity_at: Option<Timestamp>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MessageExtra {
    Attachment {
        filename: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        content_type: Option<String>,
        #[serde(default)]
        size_bytes: u64,
    },
    Embed {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    Poll,
    VoiceMessage,
    Sticker {
        name: String,
    },
    Thread,
    /// Content the SDK reported but Litecord cannot render. UI should offer
    /// "Open in Discord".
    Unsupported {
        kind: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Message {
    pub id: MessageId,
    pub conversation_id: ConversationId,
    pub author_id: UserId,
    pub content: Arc<str>,
    pub sent_at: Timestamp,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub edited_at: Option<Timestamp>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<MessageId>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub extras: Vec<MessageExtra>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lobby {
    pub id: LobbyId,
    #[serde(default)]
    pub member_ids: Vec<UserId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub linked_channel_id: Option<ChannelId>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VoiceParticipant {
    pub user_id: UserId,
    #[serde(default)]
    pub speaking: bool,
    #[serde(default)]
    pub self_muted: bool,
    #[serde(default)]
    pub self_deafened: bool,
}

/// Local voice session state (V1 §15). Transport is Discord's job.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VoiceState {
    pub connected: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lobby_id: Option<LobbyId>,
    pub muted: bool,
    pub deafened: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_device: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_device: Option<String>,
    pub output_volume: f32,
    pub noise_suppression: bool,
    pub push_to_talk: bool,
    #[serde(default)]
    pub participants: Vec<VoiceParticipant>,
}

impl Default for VoiceState {
    fn default() -> Self {
        Self {
            connected: false,
            lobby_id: None,
            muted: false,
            deafened: false,
            input_device: None,
            output_device: None,
            output_volume: 1.0,
            noise_suppression: true,
            push_to_talk: false,
            participants: Vec::new(),
        }
    }
}

/// Session/connection lifecycle (V1 §5). No UI feature may assume `Ready`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(tag = "state", rename_all = "snake_case")]
pub enum SessionState {
    #[default]
    LoggedOut,
    Authorizing,
    Connecting,
    Hydrating,
    Ready,
    Reconnecting,
    Offline,
    /// Error message is already sanitized (no secrets).
    Error {
        message: String,
    },
}

impl SessionState {
    pub fn is_online(&self) -> bool {
        matches!(self, SessionState::Ready | SessionState::Hydrating)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_serialization_roundtrip() {
        let m = Message {
            id: MessageId(10),
            conversation_id: ConversationId(20),
            author_id: UserId(30),
            content: "hello".into(),
            sent_at: Timestamp(1_000),
            edited_at: None,
            reply_to: None,
            extras: vec![MessageExtra::Attachment {
                filename: "a.png".into(),
                content_type: Some("image/png".into()),
                size_bytes: 12,
            }],
        };
        let json = serde_json::to_value(&m).unwrap();
        assert_eq!(json["id"], "10");
        assert_eq!(json["extras"][0]["type"], "attachment");
        let back: Message = serde_json::from_value(json).unwrap();
        assert_eq!(back, m);
    }

    #[test]
    fn str_enums_roundtrip() {
        for k in RelationshipKind::ALL {
            assert_eq!(RelationshipKind::parse(k.as_str()).unwrap(), *k);
        }
        assert_eq!(PresenceStatus::DoNotDisturb.as_str(), "dnd");
        assert_eq!(
            serde_json::to_string(&PresenceStatus::DoNotDisturb).unwrap(),
            "\"dnd\""
        );
    }

    #[test]
    fn channel_capabilities() {
        let c = ChannelCapabilities::DISCOVERABLE | ChannelCapabilities::OPEN_EXTERNAL;
        assert!(c.contains(ChannelCapabilities::DISCOVERABLE));
        assert!(!c.contains(ChannelCapabilities::READABLE));
    }
}
